name: Packaging the framework
run-name: ${{ github.actor }} packaging your framework ðŸš€

on: push

jobs:
  package-framework:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
    #   - name: Build
    #     run: echo ${{ github.sha }} > Release.txt
    #   - name: Test
    #     run: cat Release.txt
      - name: Zip
        run: zip -r '${{ github.ref_name }}-${{ github.sha }}-framework.zip' disty-craft-framework   
      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: ${{ github.ref_name }}-${{ github.sha }}-framework.zip